### ISSUE TITLE
Submission to the Official Ports Tree?

### ISSUE THREAD

**Issue by arcanumbridge** [psa/act-runner-freebsd-port#1]
Do you have plans to submit this to the official ports tree?  If not, would you be opposed to someone else doing that?

**Comment by arcanumbridge** [comment]
[act-runner.diff.txt](https://github.com/psa/act-runner-freebsd-port/files/14419884/act-runner.diff.txt)
Attached a diff against the main ports tree with a bunch of hardcode clean-ups.  Let me know if this still works in your use cases, I've tried to preserve that structure, but making portlint happy.

**Comment by psa** [comment]
I don't have time to add it to ports right now. If you've got the time to do that, feel free.

**Comment by arcanumbridge** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275129
